language: android
android:
  components:

    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    - sys-img-armeabi-v7a-android-26

    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
