language: android

matrix:
  include:

      services:
        - docker
      before_install:
        - source .scripts/prepare-container-with-infer.sh
        # run container with installed Infer
        - docker run -itd $INFER_IMAGE_NAME
        # copy build folder ("infer-plugin") to container
        - docker cp $TRAVIS_BUILD_DIR $(docker ps -q):/
android:
  components:
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-tv-l

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - docker pull ocaml/opam2 
    - git clone https://github.com/facebook/infer.git
    - cd infer
    - ./build-infer.sh java
    - export PATH=`pwd`/infer/bin:$PATH
    - infer run -- gradle build
