language: android

android:
  components:
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-tv-l

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - curl -OL "https://github.com/facebook/infer/releases/tag/v0.15.0/infer-linux64-v0.15.0.tar.xz" | sudo tar -C /opt -xJ 
    - ln -s "/opt/infer-linux64-v$VERSION/bin/infer"
    - export PATH=`pwd`/infer/bin:$PATH
    - infer run -- ./gradlew build
