language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-tv-l

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    
    - 
    - export PATH=`pwd`/infer/bin:$PATH
    - infer run -- gradle build
