language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-tv-l

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    
    - wget -O Dockerfile https://raw.githubusercontent.com/facebook/infer/master/docker/Dockerfile
    - wget -O run.sh https://raw.githubusercontent.com/facebook/infer/master/docker/run.sh
    - sh run.sh
    - export PATH=`pwd`/infer/bin:$PATH
    - infer run -- gradle build
